### ISSUE TITLE
Black screen without any response.

### ISSUE THREAD

**Issue by diigu** [tluck/Lenovo-T460-Clover#10]
Hi, I read your post and also https://octoperf.com/blog/2018/10/22/thinkpad-t460-how-to-install-macos/.
I'm using T460s (i7 6600u/16g/512g SSD/HD 520).
In others case, their screenshot of clover home screen, the first option is "boot macos install from install macos xxxxxxx", but my case is "start ueft shell 64", seems that clover does not recognize my macos disk partition.
Then I try to use "start ueft shell 64", but it only shows black screen without any response.
I already config the correct BIOS CONFIG, MACOS USB INSTALLER.The picture below is my macos USB installer, the first partition is EFI, the second is macos.
![](https://s1.ax2x.com/2018/12/18/5QlEFJ.png)
Thanks a lot.

**Comment by tluck** [comment]
hmm. i have no idea why it wont boot Clover? are you sure you have copied the ESP stuff from here to your USB ESP?  and boot from USB you should at at least see Clover? make sure you set the bios up:

Security > Memory Protection > Execution Prevention: Set to Enabled,
Security > Virtualization: disable all options,
Security > Secure Boot Configuration: disable Secure Boot
Startup > UEFI/Legacy Boot: Set to UEFI Only and CMS Support to No

you may have to wipe and reformat your main SSD since the default layout on the disk from Lenovo or Windows puts things in expected locations etc. 

Really nice job to @jerome on octoperf site - who created a fantastic guide with step by step pictures!

**Comment by diigu** [comment]
> hmm. i have no idea why it wont boot Clover? are you sure you have copied the ESP stuff from here to your USB ESP? and boot from USB you should at at least see Clover? make sure you set the bios up:
> 
> Security > Memory Protection > Execution Prevention: Set to Enabled,
> Security > Virtualization: disable all options,
> Security > Secure Boot Configuration: disable Secure Boot
> Startup > UEFI/Legacy Boot: Set to UEFI Only and CMS Support to No
> 
> you may have to wipe and reformat your main SSD since the default layout on the disk from Lenovo or Windows puts things in expected locations etc.
> 
> Really nice job to @jerome on octoperf site - who created a fantastic guide with step by step pictures!

The writer sofrware problem, I write again in macos it success.

**Comment by diigu** [comment]
But for some reason, my t460s "PrtSc" key not working, Karabiner viewer just cannot recognize "PrtSc" key event. 
VoodooPS2Keyboard.kext installed.
What configure item causes these in "https://github.com/tluck/Lenovo-T460-Clover/blob/master/EFI/CLOVER/kexts/Other/VoodooPS2Controller.kext/Contents/PlugIns/VoodooPS2Keyboard.kext/Contents/Info.plist"?
